baseURL = "http://example.org/"
languageCode = "en-us"
title = "Your Desired Site Title"

[params]
  description = "A minimal blog template inspired by firchwm.xyz"
  author = "f1pwe"
  github = "f1pwe"
  twitter = "f1pwe"
  showSocial = true
  postsPerPage = 5
  dateFormat = "2006-01-02"

[markup]
  [markup.highlight]
    style = "monokai"

