baseURL = "http://example.org/"
languageCode = "en-us"
title = "Your Site Title"

[params]
  description = "Your site description"
  author = "Your Name"
  github = "yourgithub"
  twitter = "yourtwitter"
  showSocial = true
  
  # Neo theme options
  showConstruction = true
  showWebring = true
  webringPrev = "#"
  webringNext = "#"
  webringRandom = "#"
  webringName = "minimalist"
  show88x31 = true
  showVisitorCounter = true
  visitorCount = "000042"
  linksPage = true

[markup]
  [markup.highlight]
    style = "monokai"

