name = "Minimal"
license = "MIT"
licenselink = "https://github.com/F1PWE/minimalt/blob/main/LICENSE"
description = "A minimalist, monospaced Hugo theme"
homepage = "https://github.com/F1PWE/minimalt"
tags = ["blog", "minimal", "dark", "responsive"]
features = ["blog", "dark mode", "responsive"]
min_version = "0.80.0"

[author]
  name = "f1pwe"
  homepage = "https://github.com/f1pwe"